FROM fedora:32

USER root

VOLUME ["/root/rpmbuild"]

RUN true \
  && dnf install -y --setopt=skip_missing_names_on_install=False \
    git \
    rpm-build \
    rpmdevtools \
    rpmlint \
    rsync \
    ShellCheck \
  && dnf clean all \
  && rm -rf /var/cache/dnf

